# Generated by Django 3.2.7 on 2021-10-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_active',
        ),
    ]
