# Generated by Django 3.2.7 on 2021-11-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_compositions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compositions',
            options={'verbose_name': 'Composition', 'verbose_name_plural': 'Compositions'},
        ),
    ]
