# Generated by Django 3.2.7 on 2021-10-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_man', models.ImageField(upload_to='Banner/')),
                ('banner_women', models.ImageField(upload_to='Banner/')),
                ('banner', models.ImageField(upload_to='Banner/')),
            ],
        ),
        migrations.CreateModel(
            name='BaseInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_instagram', models.CharField(default='Instagram', editable=False, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='instagram/')),
                ('instagram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.baseinstagram')),
            ],
        ),
    ]
